#! /bin/bash

unset GREP_OPTIONS
completed=`daylog -c`
todo=$(expr $TIMING_GOAL_MIN - $completed)
time_left=$(expr $(($(gdate -d "today $TIMING_DAY_END" +%s) - $(gdate +%s))) / 60)

echo $(expr $time_left - $todo)
