#! /bin/bash

set -f
ACTION="$@"

# Use "gdate" on BSD and the ordinary date on Linux
[[ `uname` == 'Linux' ]] && GDATE="date" || GDATE="gdate"

TODAY=`$GDATE --rfc-3339 date`
NOW=`date +%H:%M`

DAY_HEADER="= $TODAY"

# Append date header if needed
if ! grep -Fxq "$DAY_HEADER" "$TIMING_LOGFILE"
then
    echo $DAY_HEADER >> "$TIMING_LOGFILE"
fi

echo $NOW ${ACTION:-c} >> "$TIMING_LOGFILE"

tail "$TIMING_LOGFILE"
